export enum ECategory {
  RPG = 'RPG',
  ACTION = 'ACTION',
  ADVENTURE = 'ADVENTURE',
  STRATEGY = 'STRATEGY',
  FPS = 'FPS',
  MULTIPLAYER = 'MULTIPLAYER',
  OPEN_WORLD = 'OPEN_WORLD',
  FANTASY = 'FANTASY',
  SCI_FI = 'SCI_FI',
  COMPETITIVE = 'COMPETITIVE',
}
